name: Issue -> Auto Patch

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  from-issue:
    runs-on: ubuntu-latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to production branch
        run: |
          # production 브랜치로 확실히 전환
          if git show-ref --verify --quiet refs/heads/production; then
            git checkout production
          else
            git checkout -b production
          fi

      - name: Extract patch JSON from issue body
        id: extract
        run: |
          body=$(printf "%s" "${{ github.event.issue.body }}")
          # 본문에서 첫 '{'부터 마지막 '}'까지를 JSON으로 추출 (간단/견고 버전)
          json=$(echo "$body" | awk 'BEGIN{f=0} /\{/{f=1} {if(f)print} /\}/{if(f){print; exit}}')
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "$json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Save to queue file and commit
        run: |
          mkdir -p patches/queue
          FN="patches/queue/issue-${{ github.event.issue.number }}.patch.json"
          printf "%s" "${{ steps.extract.outputs.json }}" > "$FN"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FN"
          git commit -m "queue: issue #${{ github.event.issue.number }}"
          git push origin production
