name: Issue -> Queue Patch

on:
  issues:
    types: [opened]   # 이슈가 생성되면 바로 실행

permissions:
  contents: write
  issues: read

jobs:
  queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Extract patch JSON from issue body
        id: extract
        shell: bash
        run: |
          body="${{ github.event.issue.body }}"
          echo "$body" > issue_body.txt
          # 본문에서 첫 '{' ~ 마지막 '}' 까지를 JSON으로 추출
          json=$(awk 'BEGIN{f=0} /\{/{f=1} {if(f)print} /\}/{if(f){print; exit}}' issue_body.txt)
          if [ -z "$json" ]; then
            echo "❌ No JSON found in issue body"; exit 1
          fi
          echo "json<<'EOF'" >> $GITHUB_OUTPUT
          echo "$json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Save to queue and commit
        shell: bash
        run: |
          mkdir -p patches/queue
          fn="patches/queue/issue-${{ github.event.issue.number }}.patch.json"
          printf '%s' "${{ steps.extract.outputs.json }}" > "$fn"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$fn"
          git commit -m "queue: issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push origin HEAD:production
